site_name: Proton-docs
theme: readthedocs
repo_url: https://github.com/SugarLam1207/Proton-docs-template

nav:
- Home:
 - Index:index.md
- 'Hardware Guide':
 - 'Hardware Checklist'
 - 'Hardware Installation'
 - 'Network Environment Setup'
 - 'Server Deployment'
 - 'One-click Deployment'
- 'System Guide':
 - 'Quick start':quickstart.md
 - 'Employee Management and Permissions':
 - 'Order Management':
 - 'Payment Function':
 - 'Other Order Types':
 - 'Third-party Orders':
 - 'Report Center':
 - 'Offline Mode':
- Advanced:
 - 'Flexible Menu':
- FAQ:
 - 'Common Issues':
 - Troubleshooting:
- 'Contact Us':
 - 'Technical Support':
 - Feedback:
