site_name: Proton-docs
theme: readthedocs
repo_url: https://github.com/SugarLam1207/Proton-docs-template

nav:
- Home: index.md
- 'Getting started': gettingstarted.md
- 'What's New': history.md
- FAQ: faq.md

- 'More Info':
  - 'Contact Us': more-info/schema-downgrading.md
  - 'Supporting': more-info/script-providers.md
