[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Solutions Playbook"
authors = [{name = "Jake Saltzman", email = "jacob.saltzman@macedontechnologies.com"}]
dynamic = ["version", "description"]
