[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "avs1416-template-repo"
authors = [{name = "Ard van Someren", email = "ard.van.someren@gmail.com"}]
dynamic = ["version", "description"]
