name = "Traxsense"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "An intelligent asset management solution which enables your business to interface with the real world through IoT technology. Through intuitive task management, your business can gain real-world benefits though easily integrating your business into our platform."

homepage = "https://github.com/h-enk/doks"
demosite = "https://doks.netlify.app"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "Bluerain Technologies"
  homepage = "https://rfid.co.za"
